InitialSetup

diff --git a/buildroot/share/git/mfpub b/buildroot/share/git/mfpub
--- a/buildroot/share/git/mfpub
+++ b/buildroot/share/git/mfpub
@@ -9,9 +9,7 @@
 # any permanent changes to 'master'.
 #
 
-[[ $# < 2 && $1 != "-h" && $1 != "--help" ]] || { echo "Usage: `basename $0` [branch]" 1>&2 ; exit 1; }
-
-MFINFO=$(mfinfo "$@") || exit 1
+MFINFO=$(mfinfo "$@") || exit
 IFS=' ' read -a INFO <<< "$MFINFO"
 ORG=${INFO[0]}
 FORK=${INFO[1]}
@@ -26,66 +24,52 @@ fi
 
 if [[ $BRANCH == "gh-pages" ]]; then
   echo "Can't build from 'gh-pages.' Only the Jekyll branches (based on 'master')."
+  bundle exec jekyll serve --watch
   exit
+fi
+
+if [[ $BRANCH != "master" ]]; then
+  echo "Don't forget to update and push 'master'!"
+  # GOJF Card
+  git stash
 fi
 
 # Check out the named branch (or stay in current)
 git checkout $BRANCH
 
-echo "Stashing any changes to files..."
-echo "Don't forget to update and push 'master'!"
-# GOJF Card
-[[ $(git stash) != "No local "* ]] && HAS_STASH=1
+echo "Generating MarlinDocumentation..."
 
 COMMIT=$( git log --format="%H" -n 1 )
 
 # Clean out changes and other junk in the branch
+git reset --hard
 git clean -d -f
 
 # Push 'master' to the fork and make a proper PR...
 if [[ $BRANCH == "master" ]]; then
 
-  # Don't lose upstream changes!
-  git fetch upstream
-
-  # Rebase onto latest master
-  if git rebase upstream/master; then
+  if [[ $FORK == "MarlinFirmware" ]]; then
 
     # Allow working directly with the main fork
-    echo
-    echo -n "Pushing to origin/master... "
-    git push -f origin
-
-    echo
-    echo -n "Pushing to upstream/master... "
     git push -f upstream
 
   else
 
-    echo "Merge conflicts? Stopping here."
-    exit
+    if [ -z "$(git branch -vv | grep ^\* | grep \\[origin)" ]; then firstpush; fi
 
-  fi
-
-else
-
-  if [ -z "$(git branch -vv | grep ^\* | grep \\\[origin)" ]; then
-    firstpush
-  else
-    echo
-    echo -n "Pushing to origin/$BRANCH... "
     git push -f origin
-  fi
 
-  TOOL=$(which gnome-open xdg-open open | awk '{ print $1 }')
-  URL="https://github.com/$ORG/$REPO/compare/$TARG...$FORK:$BRANCH?expand=1"
+    TOOL=$(which gnome-open xdg-open open | awk '{ print $1 }')
+    URL="https://github.com/$ORG/$REPO/compare/$TARG...$FORK:$BRANCH?expand=1"
 
-  if [ -z "$TOOL" ]; then
-    echo "Can't find a tool to open the URL:"
-    echo $URL
-  else
-    echo "Opening a New PR Form..."
-    "$TOOL" "$URL"
+    if [ -z "$TOOL" ]; then
+      echo "Can't find a tool to open the URL:"
+      echo $URL
+    else
+      echo "Opening a New PR Form..."
+      "$TOOL" "$URL"
+    fi
+
   fi
 
 fi
@@ -93,11 +77,6 @@ fi
 # Uncomment to compress the final html files
 # mv ./_plugins/jekyll-press.rb-disabled ./_plugins/jekyll-press.rb
 # bundle install
-
-echo
-echo "Generating MarlinDocumentation..."
-
-rm -rf _site
 
 # build the site statically and proof it
 bundle exec jekyll build --profile --trace --no-watch
@@ -111,37 +90,17 @@ rsync -av _site/ ${TMPFOLDER}/
 git reset --hard
 git clean -d -f
 
-# Copy built-site into the gh-pages branch
-git checkout gh-pages || { echo "Something went wrong!"; exit 1; }
+# Sync built-site with gh-pages
+git checkout gh-pages
 rsync -av ${TMPFOLDER}/ ./
-
-opensite() {
-  TOOL=$(which gnome-open xdg-open open | awk '{ print $1 }')
-  URL="http://marlinfw.org/"
-  if [ -z "$TOOL" ]; then
-    echo "Can't find a tool to open the URL:"
-    echo $URL
-  else
-    echo "Opening the site in the browser..."
-    "$TOOL" "$URL"
-  fi
-}
 
 # Commit and push the new live site directly
 git add --all
 git commit --message "Built from ${COMMIT}"
-git push upstream | {
-  while IFS= read -r line
-  do
-    [[ $line =~ "gh-pages -> gh-pages" ]] && opensite
-    echo "$line"
-  done
-}
+git push upstream
 
 # remove the temporary folder
 rm -rf ${TMPFOLDER}
 
 # Go back to the branch we started from
 git checkout $BRANCH
-
-[[ $HAS_STASH == 1 ]] && git stash pop
